### ISSUE TITLE
P2 CSS 选择符和声明分隔

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#23]
## 代码规范：
>我们建议所有选择符和声明均需另起一行。

### 不推荐：

```css
h1, h2, h3 { 
    font-weight: normal; 
    line-height: 1.2; 
}
```
### 推荐：

```css
h1, 
h2, 
h3 { 
    font-weight: normal; 
    line-height: 1.2; 
}
```

引用：[选择符和声明分隔](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/前端工程师纳米学位样式指南%20-%20CSS.md#选择符和声明分隔)
